/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSuperadminRouteImport } from './routes/_authenticated/superadmin'
import { Route as AuthenticatedReportesRouteImport } from './routes/_authenticated/reportes'
import { Route as AuthenticatedRecurrentesRouteImport } from './routes/_authenticated/recurrentes'
import { Route as AuthenticatedProveedoresRouteImport } from './routes/_authenticated/proveedores'
import { Route as AuthenticatedProductosRouteImport } from './routes/_authenticated/productos'
import { Route as AuthenticatedPerfilEmpresaRouteImport } from './routes/_authenticated/perfil-empresa'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCuentasRouteImport } from './routes/_authenticated/cuentas'
import { Route as AuthenticatedConfiguracionRouteImport } from './routes/_authenticated/configuracion'
import { Route as AuthenticatedCobrosRouteImport } from './routes/_authenticated/cobros'
import { Route as AuthenticatedClientesRouteImport } from './routes/_authenticated/clientes'
import { Route as AuthenticatedAuditoriaRouteImport } from './routes/_authenticated/auditoria'
import { Route as AuthenticatedAsientosRouteImport } from './routes/_authenticated/asientos'
import { Route as AuthenticatedNominaIndexRouteImport } from './routes/_authenticated/nomina.index'
import { Route as AuthenticatedFacturasIndexRouteImport } from './routes/_authenticated/facturas.index'
import { Route as AuthenticatedCotizacionesIndexRouteImport } from './routes/_authenticated/cotizaciones.index'
import { Route as AuthenticatedFacturasNuevaRouteImport } from './routes/_authenticated/facturas.nueva'
import { Route as AuthenticatedCotizacionesNuevaRouteImport } from './routes/_authenticated/cotizaciones.nueva'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSuperadminRoute = AuthenticatedSuperadminRouteImport.update({
  id: '/superadmin',
  path: '/superadmin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedReportesRoute = AuthenticatedReportesRouteImport.update({
  id: '/reportes',
  path: '/reportes',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRecurrentesRoute =
  AuthenticatedRecurrentesRouteImport.update({
    id: '/recurrentes',
    path: '/recurrentes',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProveedoresRoute =
  AuthenticatedProveedoresRouteImport.update({
    id: '/proveedores',
    path: '/proveedores',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProductosRoute = AuthenticatedProductosRouteImport.update({
  id: '/productos',
  path: '/productos',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPerfilEmpresaRoute =
  AuthenticatedPerfilEmpresaRouteImport.update({
    id: '/perfil-empresa',
    path: '/perfil-empresa',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCuentasRoute = AuthenticatedCuentasRouteImport.update({
  id: '/cuentas',
  path: '/cuentas',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedConfiguracionRoute =
  AuthenticatedConfiguracionRouteImport.update({
    id: '/configuracion',
    path: '/configuracion',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCobrosRoute = AuthenticatedCobrosRouteImport.update({
  id: '/cobros',
  path: '/cobros',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedClientesRoute = AuthenticatedClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAuditoriaRoute = AuthenticatedAuditoriaRouteImport.update({
  id: '/auditoria',
  path: '/auditoria',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAsientosRoute = AuthenticatedAsientosRouteImport.update({
  id: '/asientos',
  path: '/asientos',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNominaIndexRoute =
  AuthenticatedNominaIndexRouteImport.update({
    id: '/nomina/',
    path: '/nomina/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFacturasIndexRoute =
  AuthenticatedFacturasIndexRouteImport.update({
    id: '/facturas/',
    path: '/facturas/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCotizacionesIndexRoute =
  AuthenticatedCotizacionesIndexRouteImport.update({
    id: '/cotizaciones/',
    path: '/cotizaciones/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFacturasNuevaRoute =
  AuthenticatedFacturasNuevaRouteImport.update({
    id: '/facturas/nueva',
    path: '/facturas/nueva',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCotizacionesNuevaRoute =
  AuthenticatedCotizacionesNuevaRouteImport.update({
    id: '/cotizaciones/nueva',
    path: '/cotizaciones/nueva',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/asientos': typeof AuthenticatedAsientosRoute
  '/auditoria': typeof AuthenticatedAuditoriaRoute
  '/clientes': typeof AuthenticatedClientesRoute
  '/cobros': typeof AuthenticatedCobrosRoute
  '/configuracion': typeof AuthenticatedConfiguracionRoute
  '/cuentas': typeof AuthenticatedCuentasRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/perfil-empresa': typeof AuthenticatedPerfilEmpresaRoute
  '/productos': typeof AuthenticatedProductosRoute
  '/proveedores': typeof AuthenticatedProveedoresRoute
  '/recurrentes': typeof AuthenticatedRecurrentesRoute
  '/reportes': typeof AuthenticatedReportesRoute
  '/superadmin': typeof AuthenticatedSuperadminRoute
  '/cotizaciones/nueva': typeof AuthenticatedCotizacionesNuevaRoute
  '/facturas/nueva': typeof AuthenticatedFacturasNuevaRoute
  '/cotizaciones/': typeof AuthenticatedCotizacionesIndexRoute
  '/facturas/': typeof AuthenticatedFacturasIndexRoute
  '/nomina/': typeof AuthenticatedNominaIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/asientos': typeof AuthenticatedAsientosRoute
  '/auditoria': typeof AuthenticatedAuditoriaRoute
  '/clientes': typeof AuthenticatedClientesRoute
  '/cobros': typeof AuthenticatedCobrosRoute
  '/configuracion': typeof AuthenticatedConfiguracionRoute
  '/cuentas': typeof AuthenticatedCuentasRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/perfil-empresa': typeof AuthenticatedPerfilEmpresaRoute
  '/productos': typeof AuthenticatedProductosRoute
  '/proveedores': typeof AuthenticatedProveedoresRoute
  '/recurrentes': typeof AuthenticatedRecurrentesRoute
  '/reportes': typeof AuthenticatedReportesRoute
  '/superadmin': typeof AuthenticatedSuperadminRoute
  '/cotizaciones/nueva': typeof AuthenticatedCotizacionesNuevaRoute
  '/facturas/nueva': typeof AuthenticatedFacturasNuevaRoute
  '/cotizaciones': typeof AuthenticatedCotizacionesIndexRoute
  '/facturas': typeof AuthenticatedFacturasIndexRoute
  '/nomina': typeof AuthenticatedNominaIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authenticated/asientos': typeof AuthenticatedAsientosRoute
  '/_authenticated/auditoria': typeof AuthenticatedAuditoriaRoute
  '/_authenticated/clientes': typeof AuthenticatedClientesRoute
  '/_authenticated/cobros': typeof AuthenticatedCobrosRoute
  '/_authenticated/configuracion': typeof AuthenticatedConfiguracionRoute
  '/_authenticated/cuentas': typeof AuthenticatedCuentasRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/perfil-empresa': typeof AuthenticatedPerfilEmpresaRoute
  '/_authenticated/productos': typeof AuthenticatedProductosRoute
  '/_authenticated/proveedores': typeof AuthenticatedProveedoresRoute
  '/_authenticated/recurrentes': typeof AuthenticatedRecurrentesRoute
  '/_authenticated/reportes': typeof AuthenticatedReportesRoute
  '/_authenticated/superadmin': typeof AuthenticatedSuperadminRoute
  '/_authenticated/cotizaciones/nueva': typeof AuthenticatedCotizacionesNuevaRoute
  '/_authenticated/facturas/nueva': typeof AuthenticatedFacturasNuevaRoute
  '/_authenticated/cotizaciones/': typeof AuthenticatedCotizacionesIndexRoute
  '/_authenticated/facturas/': typeof AuthenticatedFacturasIndexRoute
  '/_authenticated/nomina/': typeof AuthenticatedNominaIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/asientos'
    | '/auditoria'
    | '/clientes'
    | '/cobros'
    | '/configuracion'
    | '/cuentas'
    | '/dashboard'
    | '/perfil-empresa'
    | '/productos'
    | '/proveedores'
    | '/recurrentes'
    | '/reportes'
    | '/superadmin'
    | '/cotizaciones/nueva'
    | '/facturas/nueva'
    | '/cotizaciones/'
    | '/facturas/'
    | '/nomina/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/asientos'
    | '/auditoria'
    | '/clientes'
    | '/cobros'
    | '/configuracion'
    | '/cuentas'
    | '/dashboard'
    | '/perfil-empresa'
    | '/productos'
    | '/proveedores'
    | '/recurrentes'
    | '/reportes'
    | '/superadmin'
    | '/cotizaciones/nueva'
    | '/facturas/nueva'
    | '/cotizaciones'
    | '/facturas'
    | '/nomina'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/signup'
    | '/_authenticated/asientos'
    | '/_authenticated/auditoria'
    | '/_authenticated/clientes'
    | '/_authenticated/cobros'
    | '/_authenticated/configuracion'
    | '/_authenticated/cuentas'
    | '/_authenticated/dashboard'
    | '/_authenticated/perfil-empresa'
    | '/_authenticated/productos'
    | '/_authenticated/proveedores'
    | '/_authenticated/recurrentes'
    | '/_authenticated/reportes'
    | '/_authenticated/superadmin'
    | '/_authenticated/cotizaciones/nueva'
    | '/_authenticated/facturas/nueva'
    | '/_authenticated/cotizaciones/'
    | '/_authenticated/facturas/'
    | '/_authenticated/nomina/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/superadmin': {
      id: '/_authenticated/superadmin'
      path: '/superadmin'
      fullPath: '/superadmin'
      preLoaderRoute: typeof AuthenticatedSuperadminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reportes': {
      id: '/_authenticated/reportes'
      path: '/reportes'
      fullPath: '/reportes'
      preLoaderRoute: typeof AuthenticatedReportesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/recurrentes': {
      id: '/_authenticated/recurrentes'
      path: '/recurrentes'
      fullPath: '/recurrentes'
      preLoaderRoute: typeof AuthenticatedRecurrentesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/proveedores': {
      id: '/_authenticated/proveedores'
      path: '/proveedores'
      fullPath: '/proveedores'
      preLoaderRoute: typeof AuthenticatedProveedoresRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/productos': {
      id: '/_authenticated/productos'
      path: '/productos'
      fullPath: '/productos'
      preLoaderRoute: typeof AuthenticatedProductosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/perfil-empresa': {
      id: '/_authenticated/perfil-empresa'
      path: '/perfil-empresa'
      fullPath: '/perfil-empresa'
      preLoaderRoute: typeof AuthenticatedPerfilEmpresaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cuentas': {
      id: '/_authenticated/cuentas'
      path: '/cuentas'
      fullPath: '/cuentas'
      preLoaderRoute: typeof AuthenticatedCuentasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/configuracion': {
      id: '/_authenticated/configuracion'
      path: '/configuracion'
      fullPath: '/configuracion'
      preLoaderRoute: typeof AuthenticatedConfiguracionRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cobros': {
      id: '/_authenticated/cobros'
      path: '/cobros'
      fullPath: '/cobros'
      preLoaderRoute: typeof AuthenticatedCobrosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/clientes': {
      id: '/_authenticated/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof AuthenticatedClientesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/auditoria': {
      id: '/_authenticated/auditoria'
      path: '/auditoria'
      fullPath: '/auditoria'
      preLoaderRoute: typeof AuthenticatedAuditoriaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/asientos': {
      id: '/_authenticated/asientos'
      path: '/asientos'
      fullPath: '/asientos'
      preLoaderRoute: typeof AuthenticatedAsientosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/nomina/': {
      id: '/_authenticated/nomina/'
      path: '/nomina'
      fullPath: '/nomina/'
      preLoaderRoute: typeof AuthenticatedNominaIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/facturas/': {
      id: '/_authenticated/facturas/'
      path: '/facturas'
      fullPath: '/facturas/'
      preLoaderRoute: typeof AuthenticatedFacturasIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cotizaciones/': {
      id: '/_authenticated/cotizaciones/'
      path: '/cotizaciones'
      fullPath: '/cotizaciones/'
      preLoaderRoute: typeof AuthenticatedCotizacionesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/facturas/nueva': {
      id: '/_authenticated/facturas/nueva'
      path: '/facturas/nueva'
      fullPath: '/facturas/nueva'
      preLoaderRoute: typeof AuthenticatedFacturasNuevaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cotizaciones/nueva': {
      id: '/_authenticated/cotizaciones/nueva'
      path: '/cotizaciones/nueva'
      fullPath: '/cotizaciones/nueva'
      preLoaderRoute: typeof AuthenticatedCotizacionesNuevaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAsientosRoute: typeof AuthenticatedAsientosRoute
  AuthenticatedAuditoriaRoute: typeof AuthenticatedAuditoriaRoute
  AuthenticatedClientesRoute: typeof AuthenticatedClientesRoute
  AuthenticatedCobrosRoute: typeof AuthenticatedCobrosRoute
  AuthenticatedConfiguracionRoute: typeof AuthenticatedConfiguracionRoute
  AuthenticatedCuentasRoute: typeof AuthenticatedCuentasRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedPerfilEmpresaRoute: typeof AuthenticatedPerfilEmpresaRoute
  AuthenticatedProductosRoute: typeof AuthenticatedProductosRoute
  AuthenticatedProveedoresRoute: typeof AuthenticatedProveedoresRoute
  AuthenticatedRecurrentesRoute: typeof AuthenticatedRecurrentesRoute
  AuthenticatedReportesRoute: typeof AuthenticatedReportesRoute
  AuthenticatedSuperadminRoute: typeof AuthenticatedSuperadminRoute
  AuthenticatedCotizacionesNuevaRoute: typeof AuthenticatedCotizacionesNuevaRoute
  AuthenticatedFacturasNuevaRoute: typeof AuthenticatedFacturasNuevaRoute
  AuthenticatedCotizacionesIndexRoute: typeof AuthenticatedCotizacionesIndexRoute
  AuthenticatedFacturasIndexRoute: typeof AuthenticatedFacturasIndexRoute
  AuthenticatedNominaIndexRoute: typeof AuthenticatedNominaIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAsientosRoute: AuthenticatedAsientosRoute,
  AuthenticatedAuditoriaRoute: AuthenticatedAuditoriaRoute,
  AuthenticatedClientesRoute: AuthenticatedClientesRoute,
  AuthenticatedCobrosRoute: AuthenticatedCobrosRoute,
  AuthenticatedConfiguracionRoute: AuthenticatedConfiguracionRoute,
  AuthenticatedCuentasRoute: AuthenticatedCuentasRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedPerfilEmpresaRoute: AuthenticatedPerfilEmpresaRoute,
  AuthenticatedProductosRoute: AuthenticatedProductosRoute,
  AuthenticatedProveedoresRoute: AuthenticatedProveedoresRoute,
  AuthenticatedRecurrentesRoute: AuthenticatedRecurrentesRoute,
  AuthenticatedReportesRoute: AuthenticatedReportesRoute,
  AuthenticatedSuperadminRoute: AuthenticatedSuperadminRoute,
  AuthenticatedCotizacionesNuevaRoute: AuthenticatedCotizacionesNuevaRoute,
  AuthenticatedFacturasNuevaRoute: AuthenticatedFacturasNuevaRoute,
  AuthenticatedCotizacionesIndexRoute: AuthenticatedCotizacionesIndexRoute,
  AuthenticatedFacturasIndexRoute: AuthenticatedFacturasIndexRoute,
  AuthenticatedNominaIndexRoute: AuthenticatedNominaIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
